version: '3.7'
services:
  cozify-exporter:
    build: .
    init: true
    ports:
      - 5000:5000
    volumes:
      - $HOME/.config/python-cozify/python-cozify.cfg:/root/.config/python-cozify/python-cozify.cfg
